chore: add UpdateRequests reconciliation details
kyverno/website pull request #1066
Opened 2023-12-18 14:07 UTC by realshuting

## Related issue #
https://github.com/kyverno/kyverno/pull/9157

## Proposed Changes
This PR adds failure handling logic for UR reconciliations.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

2023-12-18 14:29 UTC, MariamFahmy98 approved these changes

2023-12-18 14:35 UTC, chipzoller requested changes
Seems like this needs to also capture the new field.

2023-12-18 14:35 UTC, chipzoller commented on content/en/docs/Writing policies/generate.md
> +Note that Kyverno retries up to three times to reconcile a `Failed` `UpdateRequest`, and the `UpdateRequest` will be garbage collected if it exceeds the retry threshold.
```suggestion
Note that Kyverno will retry up to three times to reconcile an `UpdateRequest` in a `Failed` status. The `UpdateRequest` will be garbage collected if it exceeds the retry threshold.
```

2023-12-18 14:54 UTC, realshuting commented
> Seems like this needs to also capture the new field.

It's self-explained in the CR [spec](https://github.com/kyverno/kyverno/pull/9157/files#diff-65ed24ceacc89ddea618d14d404077b07db0820a18e49586f8d78a0c27cce09eR102-R107), do we want to call it out in docs?

2023-12-18 15:08 UTC, chipzoller commented
> > Seems like this needs to also capture the new field.
> 
> It's self-explained in the CR [spec](https://github.com/kyverno/kyverno/pull/9157/files#diff-65ed24ceacc89ddea618d14d404077b07db0820a18e49586f8d78a0c27cce09eR102-R107), do we want to call it out in docs?

Yes, spec-level fields are all documented [here](https://kyverno.io/docs/writing-policies/policy-settings/).

2023-12-18 15:14 UTC, realshuting commented
> > > Seems like this needs to also capture the new field.
> > 
> > 
> > It's self-explained in the CR [spec](https://github.com/kyverno/kyverno/pull/9157/files#diff-65ed24ceacc89ddea618d14d404077b07db0820a18e49586f8d78a0c27cce09eR102-R107), do we want to call it out in docs?
> 
> Yes, spec-level fields are all documented [here](https://kyverno.io/docs/writing-policies/policy-settings/).

Thanks, updated!

2023-12-30 12:58 UTC, chipzoller approved these changes

2023-12-30 12:58 UTC, merged

2023-12-30 12:58 UTC, chipzoller commented
/cherry-pick release-1-11-0