[1.12] update `time_parse` filter
kyverno/website pull request #1070
Opened 2023-12-19 12:16 UTC by dreamjz

## Related issue #
https://github.com/kyverno/kyverno/pull/9173

## Proposed Changes

Add epoch time example for `time_parse()`.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

2023-12-19 12:19 UTC, chipzoller requested changes

2023-12-19 12:19 UTC, chipzoller commented on content/en/docs/Writing policies/jmespath.md
> +- The expression `time_parse('1702691171', '1702691171')` (epoch time) results in the output of `"2023-12-16T01:46:11Z"` (UTC).
Please insert new lines between these if you're going to unfold the previous line.

2023-12-19 12:34 UTC, dreamjz commented
Have inserted new lines between each example.

2024-01-31 00:46 UTC, chipzoller approved these changes

2024-01-31 00:47 UTC, merged