Admission Controllers 101 Docs
kyverno/website pull request #1086
Opened 2023-12-28 11:50 UTC by 1Shubham7

## Related issue #

Admission Controllers is a part of Introduction section of the Docs. Closes #857 

## Proposed Changes

## Checklist

- [] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [] I have inspected the website preview for accuracy.
- [] I have signed off my issue.

2023-12-28 11:53 UTC, 1Shubham7 commented
Created this new PR and closed previous one since commits were not signed there. @anushkamittal2001 and @chipzoller please give it a review

2024-01-16 13:07 UTC, chipzoller commented
I will review this again today.

2024-01-16 13:30 UTC, chipzoller requested changes

2024-01-17 01:14 UTC, 1Shubham7 commented on content/en/docs/Introduction/admission-controllers.md
> +- **Configuration management:** Admission controllers allow you to validate the configuration of the objects running in the cluster and prevent any obvious misconfigurations from hitting your cluster
I have covered use cases outlined in your presentation and am assuming that you know some of these use cases are more specific to Kyverno while the broader topic we are addressing is admission controllers. Also please comment if we should remove the previously covered usecases.

2024-01-20 14:19 UTC, 1Shubham7 commented
Hey @chipzoller, I have added use cases you outlined in your presentation. Also use cases like "Fined-grained RBAC" and "ops automation", I found them to be more specific to Kyverno than admission controllers in general so haven't added them. Please give it a review.

2024-01-29 08:02 UTC, 1Shubham7 commented
@chipzoller, please have a look.

2024-01-29 17:42 UTC, chipzoller commented
> Hey @chipzoller, I have added use cases you outlined in your presentation. Also use cases like "Fined-grained RBAC" and "ops automation", I found them to be more specific to Kyverno than admission controllers in general so haven't added them. Please give it a review.

"ops automation", yes, is more Kyverno specific, but fine-grained RBAC is not. All validating admission controllers for the most part have this capability and is a major use case.

2024-01-30 18:24 UTC, 1Shubham7 commented
> "ops automation", yes, is more Kyverno specific, but fine-grained RBAC is not. All validating admission controllers for the most part have this capability and is a major use case.

yes, I agree "fine grained RBAC" is a major use, now that I studied about it. I misunderstood it to be something else. added it as well.

2024-02-10 12:07 UTC, chipzoller approved these changes
Thanks for kicking this off. I'm going to build on your content here.

2024-02-10 12:07 UTC, merged