docs: Add `imageIndex` field to `imageData`
kyverno/website pull request #1182
Opened 2024-03-11 17:35 UTC by NetanelK

## Related issue #
kyverno/kyverno#8273

## Proposed Changes
Add `imageIndex` to `imageData` documentation.

## Checklist

- [X] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [X] I have inspected the website preview for accuracy.
- [X] I have signed off my issue.

2024-05-29 14:28 UTC, chipzoller requested changes
Minor conflict to resolve here since we did some branch maintenance.

2024-08-25 20:58 UTC, JimBugwadia approved these changes

2024-08-25 20:59 UTC, JimBugwadia commented
@NetanelK - thanks for the contribution! Can you please resolve the conflict, so we can merge this?

2024-09-26 11:06 UTC, realshuting commented
I can't push to the forked repo, created https://github.com/kyverno/website/pull/1182. 

Thanks for sending the PR @NetanelK !

2024-09-26 11:06 UTC, closed without merging