add example for setting up grafana dashboard
kyverno/website pull request #1243
Opened 2024-05-08 13:01 UTC by anushkamittal2001

## Related issue #
N/A (recently setup grafana with kind cluster and struggled a bit)

## Proposed Changes
Add an example of setting up kyverno with grafana in a kind clusyter

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

2024-05-29 01:39 UTC, chipzoller requested changes
Hi @anushkamittal2001, see these proposed changes. Some general guidelines which will help in writing good documentation:

1. Don't use abbreviations or aliased commands. `k` may not be aliased for all users and so you should always prefer the formal, full program name `kubectl`.
2. Ensure your commands match up to the results. When you have inconsistencies in commands versus output, it's confusing for users who may not have your level of expertise.
3. Be consistent in how you write.

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +### Example: Setup Grafana with Kyverno and a Kind cluster
```suggestion
### Tutorial
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Add helm repositories
```suggestion
Add Helm repositories.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Update repos
```suggestion
Update Helm repositories.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Install Kyverno and monitoring
```suggestion
Install Kyverno and the kube-prometheus-stack Helm chart.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +k -n monitoring get po -l "release"
```suggestion
kubectl -n monitoring get po -l "release"
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Create the service monitor
```suggestion
Create the ServiceMonitor resource.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +`vi sm.yaml`
```suggestion
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Add the following service monitor yaml
```suggestion
Add the following contents to a file named `service-monitor.yaml`.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +k apply -f sm.yaml
```suggestion
kubectl apply -f service-monitor.yaml
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Apply service-monitor.yaml
```suggestion
Create the ServiceMonitor.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Add right labels
```suggestion
Add the appropriate labels.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +k label ns kyverno app.kubernetes.io/name=kyverno
```suggestion
kubectl label ns kyverno app.kubernetes.io/instance=kyverno                                                               
kubectl label ns kyverno app.kubernetes.io/name=kyverno
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Restart deployments and sts in monitoring ns
```suggestion
Restart Deployments and StatefulSets in the `monitoring` Namespace.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +k rollout restart deploy,sts -n monitoring
```suggestion
kubectl rollout restart deploy,sts -n monitoring
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Check services in monitoring ns
```suggestion
Check services in the `monitoring` Namespace.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +k get svc -n monitoring
```suggestion
kubectl get svc -n monitoring             
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Port forward the svc/monitoring-kube-prometheus-prometheus to a local port
```suggestion
Port forward the `monitoring-kube-prometheus-prometheus` Service to a local port.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +sudo kubectl port-forward svc/monitoring-kube-prometheus-prometheus 81:9090 -n monitoring
```suggestion
kubectl port-forward svc/monitoring-kube-prometheus-prometheus 81:9090 -n monitoring                                                       
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Similarly port forward the svc/monitoring-grafana to another local port
```suggestion
Similarly, port forward the `monitoring-grafana` Service to another local port.
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +k get svc -n monitoring
```suggestion
kubectl get svc -n monitoring               
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +sudo kubectl port-forward svc/monitoring-grafana -n monitoring 82:80
```suggestion
kubectl port-forward svc/monitoring-grafana -n monitoring 82:3000
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Go to Prometheus on port 81 (in this case) and check status -> Targets -> Filter for kyverno (to see if metrics are getting scraped)
```suggestion
Go to Prometheus on port 9090 and check status -> Targets -> Filter for kyverno (to see if metrics are getting scraped)
```

2024-05-29 01:39 UTC, chipzoller commented on content/en/docs/monitoring/bonus-grafana-dashboard/index.md
> +Go to Grafana on port 82 (in this case) -> Dashboards -> New ->  import -> Upload file that you get from running the below command -> Data type = Prometheus -> import
```suggestion
Go to Grafana on port 3000 -> Dashboards -> New ->  import -> Upload file that you get from running the below command -> Data type = Prometheus -> import
```

2024-06-08 11:49 UTC, chipzoller commented
@anushkamittal2001, awaiting changes here

2024-07-05 12:28 UTC, anushkamittal2001 commented
@chipzoller 

Thank you for all your suggestions, I have noted the guidelines you shared for the future! I have merged all your suggestions. Please let me know if it looks okay.

2024-07-14 19:59 UTC, chipzoller approved these changes

2024-07-14 19:59 UTC, merged