Credit to Abir Sigron
kyverno/website pull request #1344
Opened 2024-09-12 12:31 UTC by abirsigron

Added credit for the idea of using kyverno for "Assigning Node Metadata to Pods"

Following my idea to use kyverno to add node metadata to pods using kyverno policy in the kyverno slack [thread](https://kubernetes.slack.com/archives/CLGR9BJU9/p1678025399812099), including implementing the first POC

2024-09-24 06:37 UTC, realshuting commented
I'm not the author of this blog post, deferring it to @chipzoller .

2024-10-13 06:52 UTC, abirsigron commented
@chipzoller Can you approve and merge?

2024-10-13 12:06 UTC, chipzoller requested changes

2024-10-13 12:06 UTC, chipzoller commented on content/en/blog/general/assigning-node-metadata-to-pods/index.md
> +Thanks [Abir Sigron](https://github.com/abirsigron) for initiating the innovative idea and contributing to its successful implementation.
```suggestion
Thanks to [Abir Sigron](https://github.com/abirsigron) for bringing this up in Slack.
```

2024-10-13 12:46 UTC, chipzoller approved these changes

2024-10-13 19:06 UTC, JimBugwadia approved these changes

2024-10-13 19:07 UTC, merged