Update install/update/uninstall steps for Helm chart changes
kyverno/website pull request #304
Opened 2021-09-22 19:45 UTC by treydock

Signed-off-by: Trey Dockendorf <tdockendorf@osc.edu>

In response to https://github.com/kyverno/kyverno/pull/2357

For the upgrade steps, I opted for "simplest" approach where do full uninstall/re-install.  There are less simple ways to do upgrade documented in https://github.com/kyverno/kyverno/pull/2357 but wasn't sure if was good to document those steps.

2021-09-22 20:55 UTC, realshuting commented on content/en/docs/Installation/_index.md
> +Below are the steps to upgrade Kyverno to 1.5.0 from 1.4.3. The upgrade to 1.50+ requires first removing the old CRDs CRDs chart.
Duplicated `CRDs`.

2021-09-22 21:42 UTC, treydock commented on content/en/docs/Installation/_index.md
> +Below are the steps to upgrade Kyverno to 1.5.0 from 1.4.3. The upgrade to 1.50+ requires first removing the old CRDs CRDs chart.
Fixed

2021-09-22 21:47 UTC, realshuting commented
@chipzoller - can you please help review?

2021-09-22 21:47 UTC, realshuting approved these changes

2021-09-22 21:51 UTC, chipzoller commented on content/en/docs/Installation/_index.md
> +Below are the steps to upgrade Kyverno to 1.5.0 from 1.4.3. The upgrade to 1.50+ requires first removing the old CRDs chart.
Second 1.5.0 is missing a period.

2021-09-22 21:51 UTC, chipzoller requested changes
Minor comment

2021-09-23 12:40 UTC, treydock commented on content/en/docs/Installation/_index.md
> +Below are the steps to upgrade Kyverno to 1.5.0 from 1.4.3. The upgrade to 1.50+ requires first removing the old CRDs chart.
Fixed.

2021-09-23 13:36 UTC, chipzoller approved these changes

2021-10-15 19:13 UTC, merged