[1.5.0] Update docs for dynamic webhooks
kyverno/website pull request #316
Opened 2021-10-06 06:07 UTC by realshuting

Signed-off-by: ShutingZhao <shutting06@gmail.com>

Closes #314.
Closes https://github.com/kyverno/kyverno/issues/1983.

2021-10-06 07:11 UTC, JimBugwadia requested changes
So, with this feature will all existing installations switch to `Fail` from `Ignore`? Or, will this only be the default behavior for new installations?

2021-10-06 07:11 UTC, JimBugwadia commented on content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-rule-info-total.md
> +| status\_ready            | "true", "false"                  | Readiness of the policy. When ready, the policy is able to serve the admission request
Readiness of the policy. When ready, the policy is able to serve admission requests

2021-10-06 07:11 UTC, JimBugwadia commented on content/en/docs/Writing policies/webhooks.md
> +From Kyverno 1.5.0, the `mutatingWebhookConfiguration` and the `validatingWebhookConfiguration` are registered and managed dynamically based on the configured policies. Prior to this version, Kyverno
Starting with Kyverno 1.5.0, the `mutatingWebhookConfiguration` and the `validatingWebhookConfiguration` resources are registered and managed dynamically based on the configured policies. Prior to this version, Kyverno uses a wildcard webhook that allowed it to receive admission requests for all resources. With the webhook auto-configuration feature, Kyverno now only receives admission requests for select resources hence preventing unnecessary admission requests being forwarded to Kyverno. 

This feature is enabled by default in 1.5.0 and can be turned off by flag `--autoUpdateWebhooks=false`. If disabled, Kyverno creates the default webhook configurations that forwards admission requests for all resources and with `FailurePolicy` set to `Ignore`.

2021-10-06 07:11 UTC, JimBugwadia commented on content/en/docs/Writing policies/webhooks.md
> +## Configurable Fields
## Policy configurable Fields

2021-10-06 07:11 UTC, JimBugwadia commented on content/en/docs/Writing policies/webhooks.md
> +`pol.spec.failurePolicy`: FailurePolicy defines how unrecognized errors from the admission endpoint are handled. Rules within the same policy share the same failure behavior. Allowed values are Ignor
FailurePolicy defines how unrecognized errors from the admission endpoint are handled by the Kubernetes API server.

2021-10-06 07:11 UTC, JimBugwadia commented on content/en/docs/Writing policies/webhooks.md
> +`pol.spec.webhookTimeoutSeconds`: WebhookTimeoutSeconds specifies the webhook timeout for this policy. After the timeout passes, the admission request will fail based on the failure policy. The defau
After the configured time has expired, the admission request will be handled based on the failure policy. The default timeout is 10s, the value must be between 1 and 30 seconds.

2021-10-06 07:30 UTC, realshuting commented
> So, with this feature will all existing installations switch to `Fail` from `Ignore`? Or, will this only be the default behavior for new installations?

Yes, the existing webhooks will be switched to `Fail`.

2021-10-14 06:15 UTC, realshuting commented on content/en/docs/Installation/_index.md
> +Starting with Kyverno 1.5.0, the webhooks are managed dynamically based on the configured policies, see [Dynamic Webhook Configurations]((/docs/writing-policies/webhooks/)) for details. Disable auto-
Updated, thank you @chipzoller !

2021-10-19 05:54 UTC, JimBugwadia approved these changes

2021-10-19 05:54 UTC, merged