Add a supports page
kyverno/website pull request #386
Opened 2021-11-11 17:44 UTC by Anita-ihuman

This PR is a fix for #381

2021-11-11 17:52 UTC, chipzoller commented
Please use closing keywords or manually link to issues.

2021-11-11 17:53 UTC, chipzoller commented on config/_default/menus/menu.en.toml
> +  name = "Supports"
Should just be "Support"

2021-11-11 18:00 UTC, chipzoller requested changes

2021-11-11 18:11 UTC, chipzoller requested changes
"Supports" => "Support" everywhere for consistency, including the path at `content/en/support/_index.md`

2021-11-12 09:34 UTC, Anita-ihuman commented
@chipzoller please review

2021-11-12 12:33 UTC, chipzoller commented on content/en/support/_index.md
> +[Nirmata](https://nirmata.com/) is the creator of Kyverno and offers enterprise licensing with long term support, curated policy sets with compatibility testing, multi-cluster policy as code, a DevSe
"[Nirmata] offers enterprise licensing..." <== is this actually true?

2021-11-12 12:33 UTC, chipzoller reviewed
I have asked Kim about this, but I don't see anywhere that Nirmata offers an enterprise license for Kyverno, only other offerings built around it.

2021-11-12 12:59 UTC, Anita-ihuman commented
@JimBugwadia,
Please help me out with this.

2021-11-12 14:54 UTC, JimBugwadia commented
The relevant offer is called "Nirmata Enterprise Subscription for Kyverno". See:

https://nirmata.com/kyverno-enterprise/

2021-11-12 15:41 UTC, chipzoller commented
But that's not a "license" for Kyverno, that's mostly a support subscription entitlement, correct? Kyverno only has a single license and that's Apache 2.0 which includes commercial use. Just making sure we use the correct terminology here...

2021-11-13 00:37 UTC, JimBugwadia commented
> But that's not a "license" for Kyverno, that's mostly a support subscription entitlement, correct? Kyverno only has a single license and that's Apache 2.0 which includes commercial use. Just making sure we use the correct terminology here...

I see your point. @Anita-ihuman - lets change to `and offers an enterprise subscription with long term support`.

2021-11-13 03:43 UTC, chipzoller approved these changes

2021-11-13 03:44 UTC, merged