Security Section
kyverno/website pull request #400
Opened 2021-11-30 09:37 UTC by ShubhamPalriwala

Signed-off-by: ShubhamPalriwala <spalriwalau@gmail.com>

Closes #225 

@JimBugwadia Have drafted this based on our [google doc ](https://docs.google.com/document/d/1tFEo2qhsmWcjkRUu3QxYYYbr0BQluskS_0iEV_GspgA/edit#heading=h.481dqd5dgjxh). We can continue making changes here now.

2021-12-02 17:40 UTC, chipzoller commented on content/en/security/_index.md
> +```
Please try to use languages for all fenced code blocks.

2021-12-07 08:27 UTC, JimBugwadia commented
@ShubhamPalriwala @chipzoller - I moved the security section to:

https://deploy-preview-400--kyverno.netlify.app/docs/security/

The roles section is dependent on this PR: https://github.com/kyverno/kyverno/pull/2799

Please review, so we can wrap this up!

2021-12-07 08:31 UTC, JimBugwadia approved these changes

2021-12-07 08:47 UTC, ShubhamPalriwala commented
Hey @JimBugwadia, this is very well crafted!
Looks great to me just a couple of small suggestions:
- Can we just have the command inside the backticks so that the users can directly copy it and use it?
![image](https://user-images.githubusercontent.com/55556994/144995845-de61c03c-d0bb-4444-b0ff-659869ccf26f.png)

- Can we now remove the signing and SBOM from the Installation Page [here](https://deploy-preview-400--kyverno.netlify.app/docs/installation/#verifying-kyverno-image-signatures-using-cosign) as it seems redundant!

If you want. I can make these small changes and commit them

2021-12-07 09:13 UTC, JimBugwadia commented
@ShubhamPalriwala - sounds good. Please proceed with the proposed changes.

2021-12-07 09:35 UTC, ShubhamPalriwala commented
Done! @JimBugwadia Everything looks good to me now

2021-12-07 17:14 UTC, chipzoller commented on content/en/docs/security/_index.md
> +If find or suspect a vulnerability please send an email to the security group at kyverno-security@googlegroups.com with the following information:
"If you find or suspect a vulnerability, please email the security group at..."

2021-12-07 17:15 UTC, chipzoller commented on content/en/docs/security/_index.md
> +Kyverno security response team will send an initial acknowledgement of the disclosure in 3-5 working days. Once the vulnerability and mitigation are confirmed, the team will plan to release any neces
"The Kyverno security response team..."

2021-12-07 17:17 UTC, chipzoller commented on content/en/docs/security/_index.md
> +With every release, Kyverno uploads the following artifacts:
Although they aren't on the releases page, we also upload the container images stated here: https://github.com/orgs/kyverno/packages?repo_name=kyverno

2021-12-07 17:18 UTC, chipzoller commented on content/en/docs/security/_index.md
> +Kyverno container images are signed using Cosign. To verify the container image, download the organization public key (https://github.com/kyverno/kyverno/blob/main/cosign.pub) into a file named cosig
Link to Cosign project.

"file named `cosign.pub`" (files as code formatted)

2021-12-07 17:19 UTC, chipzoller commented on content/en/docs/security/_index.md
> +All 3 of Kyverno images can be verified: `kyvernopre`, `kyverno`, and `kyverno-cli`.
"All three Kyverno images, <insert image names here>, can be verified."

2021-12-07 17:19 UTC, chipzoller commented on content/en/docs/security/_index.md
> +An SBOM (Software Bill of Materials) in CycloneDX JSON format is published for each Kyverno release. To download the SBOM for a specific version, install cosign and run:
"Cosign" (proper noun)

2021-12-07 17:21 UTC, chipzoller commented on content/en/docs/security/_index.md
> +The Kubernetes SIG Security team has defined an [Admission Control Threat Model](https://docs.google.com/document/d/1tQTZ6wrD2udbUGL7xhc3SRxqyTvS8FQUlL59KHYHcY8/edit#heading=h.bx94h7ux7k41). It is hi
Link to Kubernetes SIG Security would be nice.

2021-12-07 17:21 UTC, chipzoller commented on content/en/docs/security/_index.md
> +The following pod security best practices are followed for all Kyverno containers:
"Pod"

2021-12-07 17:23 UTC, chipzoller commented on content/en/docs/security/_index.md
> +Kyverno policies are configured to `fail-closed` by default. This setting can be tuned on a [per policy basis](/docs/writing-policies/policy-settings/). Kyverno uses the configured policy set to auto
`fail-closed` here isn't code and should be excluded from code formatting.

2021-12-07 17:24 UTC, chipzoller commented on content/en/docs/security/_index.md
> +At a minimum, the [pod security](/policies/pod-security/) and [best practices](/policies/?policytypes=Best%2520Practices) policy sets are recommended for use.
The Pod Security Standard

2021-12-07 17:24 UTC, chipzoller commented on content/en/docs/security/_index.md
> +Kyverno policies can be used to mutate and generate configurations, and access to policies should be protected using RBAC.
"...and generate resources..."

2021-12-07 17:25 UTC, chipzoller requested changes
Please see in-line comments.

2021-12-07 17:26 UTC, chipzoller commented
Hold for 1.6.0

2021-12-08 00:01 UTC, JimBugwadia commented
Thanks @chipzoller! I've addressed the comments.

2021-12-08 13:49 UTC, chipzoller approved these changes

2021-12-08 22:20 UTC, JimBugwadia approved these changes

2021-12-09 13:08 UTC, merged