Namespace Specific ValidationFailureAction
kyverno/website pull request #453
Opened 2022-01-27 13:08 UTC by ojhaarjun1

Closes #410 

Signed-off-by: Kumar Mallikarjuna <kumarmallikarjuna1@gmail.com>

2022-01-31 14:50 UTC, chipzoller commented on content/en/docs/Writing policies/validate.md
> +        resources:
Let's add `any` here since this is the new standard.

2022-01-31 14:50 UTC, chipzoller requested changes
Inline comments

2022-02-05 00:19 UTC, chipzoller commented
Can we close this out, please?

2022-02-05 12:05 UTC, ojhaarjun1 commented on content/en/docs/Writing policies/validate.md
> +In the above policy, for Namespace `default`, validation failure action is set to `enforce` and for Namespace `test`, it's set to `audit`. For all other Namespaces, the action defaults to the `valida
In this context, "validation failure action" refers to the action and not the attribute `validationFailureAction`. Writing `validationFailureAction` would instead imply changing the attribute value internally based on the namespace.

2022-02-05 12:11 UTC, ojhaarjun1 commented
@chipzoller - Added inline comments to the example YAML. Is this what you meant?

2022-02-05 13:11 UTC, chipzoller approved these changes

2022-02-05 13:11 UTC, merged