Added generate tag in Cli test section
kyverno/website pull request #603
Opened 2022-08-24 03:30 UTC by chetak123

## Related issue #553 

## Proposed Changes

I have added the `generatedResource` tag in test cli section along an [example](https://github.com/kyverno/policies/tree/main/best-practices/add_network_policy) 

## Checklist

- [] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [] I have inspected the website preview for accuracy.
- [] I have signed off my issue.

2022-08-29 20:01 UTC, chipzoller commented
@chetak123 please complete the PR issue template and use closing keywords or manually link to the issue this will close.

2022-08-30 08:36 UTC, shubham4443 requested changes
Hi @chetak123 thank you for opening PR for my issue!
Here are some of the changes I felt that needs to be done -
1. [This line](https://github.com/kyverno/website/blob/677f54704126df6c8f48c959e28457829b78a6ea/content/en/docs/Kyverno%20CLI/_index.md?plain=1#L697) needs to be updated. It mentions only validate and mutate policy is supported which is not the case.
2. [This line](https://github.com/kyverno/website/blob/677f54704126df6c8f48c959e28457829b78a6ea/content/en/docs/Kyverno%20CLI/_index.md?plain=1#L703) - mutate and generate rule can declare a pass

2022-08-30 08:38 UTC, shubham4443 commented on content/en/docs/Kyverno CLI/_index.md
> +In the following policy test, a `generate` policy rule is applied which generates a new resource from an existing resource present in resource.yaml. To test such policy the `generatedResource` tag is
This line could be refactored - To test `generate` policy, the addition of `generatedResource` field in the `results[]` array is must which is used to test against the resource generated by the policy.

2022-09-11 13:18 UTC, chipzoller commented
@chetak123 please help close this PR out by addressing comments. It is needed in 1.8.0 docs.

2022-09-11 20:04 UTC, chipzoller requested changes

2022-09-11 20:04 UTC, chipzoller commented on content/en/docs/Kyverno CLI/_index.md
> + Note : The resource field is being deprecated in 1.8.0 release. Please provide the resources under the resources parameter as an array in the results field
Please remove this deprecation notice. I have an [open issue](https://github.com/kyverno/kyverno/issues/4590) to eliminate it in the code as well.

2022-09-12 04:52 UTC, chetak123 commented
Hey @chipzoller I have made the required changes.

2022-09-17 21:30 UTC, chipzoller commented
@chetak123 would you mind please resolving conflicts here?

2022-10-11 13:40 UTC, chipzoller commented
@chetak123 I thank you for the PR and am incorporating your content (with attribution) in my PR #643. This was due to there being enough changes that it was easier to make them all myself.

2022-10-11 13:40 UTC, closed without merging