WIP: Blog about custom jmespath functions
kyverno/website pull request #762
Opened 2023-02-05 18:26 UTC by Vishal-Chdhry

Signed-off-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>

## Related issue: 
None

https://kubernetes.slack.com/archives/C032MM2CH7X/p1673274883889049?thread_ts=1673097525.979879&cid=C032MM2CH7X

## Proposed Changes
Creates a blog about jmespath.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

2023-02-14 12:43 UTC, chipzoller requested changes
Again, I think you can cut out the lengthy examples and just focus on use cases. You should just focus on use cases surrounding the new time-based filters and probably not attempt to discuss how Kyverno uses JMESPath, which might be a multi-part series.

2023-02-14 18:51 UTC, Vishal-Chdhry commented
@chipzoller Is this right?

2023-02-14 20:50 UTC, chipzoller reviewed
No, it's not quite what I meant. You're still just listing out all the filters very similar to what the documentation does. You're not telling a story around why they exist and some practical ways they can be used. The purpose of a blog is to tell that story, practical use, and with a conversational style.

2023-02-15 03:26 UTC, Vishal-Chdhry commented
@chipzoller okay, i think I got it!

2023-02-15 14:13 UTC, chipzoller commented on content/en/blog/general/jmespath/index.md
> +The `time_utc()` filter takes in a time in RFC 3339 format with a time offset and presents the same time in UTC/Zulu. It can be used in pair with `time_parse()` to convert it to UTC.
What I mean is all of this. Blogs don't need to list all the filters out. This is what documentation is for. Blogs tell a story around a use case in a casual style.

2023-02-15 14:13 UTC, chipzoller commented on content/en/blog/general/jmespath/index.md
> +In addition to the filters available in the upstream JMESPath library which Kyverno uses, there are also many new and custom filters developed for Kyverno's use found nowhere else. These filters augm
This is just copied directly from the documentation.

2023-03-10 14:46 UTC, chipzoller commented
Any updates here?

2023-03-11 18:53 UTC, Vishal-Chdhry commented
@chipzoller yeah i made some changes, are they okay?

2023-04-01 12:34 UTC, chipzoller approved these changes

2023-04-01 12:34 UTC, merged